# permissions for end users to edit archives.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: archive-editor-role
rules:
- apiGroups:
  - berth.kubeberth.io
  resources:
  - archives
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - berth.kubeberth.io
  resources:
  - archives/status
  verbs:
  - get
