# permissions for end users to edit cloudinits.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudinit-editor-role
rules:
- apiGroups:
  - berth.kubeberth.io
  resources:
  - cloudinits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - berth.kubeberth.io
  resources:
  - cloudinits/status
  verbs:
  - get
