# permissions for end users to edit isoimages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: isoimage-editor-role
rules:
- apiGroups:
  - berth.kubeberth.io
  resources:
  - isoimages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - berth.kubeberth.io
  resources:
  - isoimages/status
  verbs:
  - get
