# permissions for end users to view isoimages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: isoimage-viewer-role
rules:
- apiGroups:
  - berth.kubeberth.io
  resources:
  - isoimages
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - berth.kubeberth.io
  resources:
  - isoimages/status
  verbs:
  - get
