# permissions for end users to edit kubeberths.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeberth-editor-role
rules:
- apiGroups:
  - berth.kubeberth.io
  resources:
  - kubeberths
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - berth.kubeberth.io
  resources:
  - kubeberths/status
  verbs:
  - get
