---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - berth.kubeberth.io
  resources:
  - archives
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - berth.kubeberth.io
  resources:
  - archives/finalizers
  verbs:
  - update
- apiGroups:
  - berth.kubeberth.io
  resources:
  - archives/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - berth.kubeberth.io
  resources:
  - cloudinits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - berth.kubeberth.io
  resources:
  - cloudinits/finalizers
  verbs:
  - update
- apiGroups:
  - berth.kubeberth.io
  resources:
  - cloudinits/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - berth.kubeberth.io
  resources:
  - disks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - berth.kubeberth.io
  resources:
  - disks/finalizers
  verbs:
  - update
- apiGroups:
  - berth.kubeberth.io
  resources:
  - disks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - berth.kubeberth.io
  resources:
  - kubeberths
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - berth.kubeberth.io
  resources:
  - kubeberths/finalizers
  verbs:
  - update
- apiGroups:
  - berth.kubeberth.io
  resources:
  - kubeberths/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - berth.kubeberth.io
  resources:
  - loadbalancers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - berth.kubeberth.io
  resources:
  - loadbalancers/finalizers
  verbs:
  - update
- apiGroups:
  - berth.kubeberth.io
  resources:
  - loadbalancers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - berth.kubeberth.io
  resources:
  - servers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - berth.kubeberth.io
  resources:
  - servers/finalizers
  verbs:
  - update
- apiGroups:
  - berth.kubeberth.io
  resources:
  - servers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cdi.kubevirt.io
  resources:
  - datavolumes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubevirt.io
  resources:
  - virtualmachineinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubevirt.io
  resources:
  - virtualmachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
