apiVersion: berth.kubeberth.io/v1alpha1
kind: LoadBalancer
metadata:
  name: loadbalancer-sample
  namespace: kubeberth
spec:
  backends:
  - server: server-sample
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
