apiVersion: berth.kubeberth.io/v1alpha1
kind: Server
metadata:
  name: server-sample
  namespace: kubeberth
spec:
  running: true
  cpu: 2
  memory: 2Gi
  macAddress: 52:42:00:c7:90:10   # optional
  hostname: ubuntu-server
  #hostring: node-1.k8s.home.arpa  # optional
  disk:
    name: disk-sample
  cloudinit:
    name: cloudinit-sample
