apiVersion: berth.kubeberth.io/v1alpha1
kind: CloudInit
metadata:
  name: cloudinit-sample
  namespace: kubeberth
spec:
  userData: |
    #cloud-config
    timezone: Asia/Tokyo
    ssh_pwauth: True
    password: ubuntu
    chpasswd: { expire: False }
    disable_root: false
    #ssh_authorized_keys:
    #- ssh-rsa XXXXXXXXXXXXXXXXXXXXXXXXX
    package_update: true
    packages:
    - nginx
    runcmd:
    - hostname > /var/www/html/index.html
