---

apiVersion: v1
kind: Namespace
metadata:
  name: kubeberth

---

apiVersion: berth.kubeberth.io/v1alpha1
kind: KubeBerth
metadata:
  name: kubeberth
  namespace: kubeberth
spec:
  storageClassName: "longhorn"
  externalDNSDomainName: "kubeberth.k8s.arpa"

---
